### ISSUE TITLE
How to visualize the attention map？

### ISSUE THREAD

**Issue by BroHUAJI** [swathikirans/ego-rnn#5]
First of all, thank you very much for your work, it is very good.
In the paper, you visualized the attention map. Is this reflected in the code?

**Comment by swathikirans** [comment]
Hi,
the attention map visualization is not there in the code. You can refer to the following code snippet for visualization:

`normalize = transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225])
preprocess_image = transforms.Compose([
                   transforms.Scale(340),
                   transforms.CenterCrop(299)])
preprocess_tensor = transforms.Compose([
                    transforms.ToTensor(), normalize])

fl_name = 'test_file.jpg'
img_pil = Image.open(fl_name)
img_pil1 = preprocess_image(img_pil)
img_size = img_pil1.size
img_tensor = preprocess_tensor(img_pil1)
img_variable = Variable(img_tensor.unsqueeze(0).cuda())
img = np.asarray(img_pil1)
attentionMap = model(img_variable, img)
attentionMap = attentionMap.data.cpu().numpy()
attentionMap = attentionMap.reshape(7, 7)
attentionMap = attentionMap - np.min(attentionMap)
attentionMap = attentionMap / np.max(attentionMap)
attentionMap = np.uint8(255 * attentionMap)
attentionMap = cv2.resize(attentionMap, (img_size[0], img_size[1]))
heatmap = cv2.applyColorMap(attentionMap, cv2.COLORMAP_JET)
attentionMap_overlay = heatmap * 0.3 + img * 0.5
attentionMap_overlay = cv2.cvtColor(np.uint8(attentionMap_overlay), cv2.COLOR_RGB2BGR)
cv2.imwrite(fl_name_new, attentionMap_overlay)`

attentionMap can be obtained by modifying the following code to return "attentionMap" in line33:
https://github.com/swathikirans/ego-rnn/blob/master/objectAttentionModelConvLSTM.py

**Comment by BroHUAJI** [comment]
Thanks!! But when I train model, I run

`python main-run-rgb.py --dataset gtea61 
--stage 1 
--trainDatasetDir ./dataset/gtea_61/split2/train 
--outDir experiments 
--seqLen 25 
--trainBatchSize 32 
--numEpochs 300 
--lr 1e-3 
--stepSize 25 75 150 
--decayRate 0.1 
--memSize 512`

When the training is over, the model is not saved. So, I can't run stage 2. Can you tell me what happened?

**Comment by swathikirans** [comment]
Can you check if there are any files inside the directory "experiments"?

**Comment by BroHUAJI** [comment]
THANKS！I have a problem with the visual attention map code you provided.

`fl_name = 'test_file.jpg'`  

This represents the original image that you want to visualize. Am I right?

If I'm right. So, when I want to process the attention map of the entire dataset, is it necessary to change the 'test_file.jpg' step by step?

**Comment by swathikirans** [comment]
You can modify the script to loop through the images from the entire dataset.

**Comment by BroHUAJI** [comment]
Thanks for your answers！But I have some other questions.

`attentionMap = model(img_variable, img)`

What does the "model" mean? I didn't see this function in objectAttentionModelConvLSTM.py.

`cv2.imwrite(fl_name_new, attentionMap_overlay)`

What does the "fl_name_new" mean? I didn't see this parameter before.

**Comment by swathikirans** [comment]
Hi,
"model" is an instantiation of "objectAttentionModelConvLSTM.py", which is modified to output the attention maps. "fl_name_new" is the name of the output file.

**Comment by BroHUAJI** [comment]
There is an error called "TypeError: forward() takes 2 positional arguments but 3 were given
"

`attentionMap = model(img_variable, img)`

There is only one parameter input in the class attentionModel. Why there are two parameters here,?

**Comment by BroHUAJI** [comment]
Hello, there is one last question. For the forward function in the class attentionModel, where is this function used? I didn't find it.

**Comment by swathikirans** [comment]
I added a file for attention map visualization. You can find it here https://github.com/swathikirans/ego-rnn/blob/master/genAttentionMap.py

**Comment by BroHUAJI** [comment]
Thank you for your continued answers！

There is one last question. 

`from attentionMapModel import attentionMap`

What does attentionMapModel mean here？Is this module added from the official library or is it self-defined? I did‘t find this module in your code.

**Comment by swathikirans** [comment]
It is not from the official repo. It is also added in the repo.

**Comment by BroHUAJI** [comment]
Sorry, my bad. It works. Thanks again!
