### ISSUE TITLE
Model is not saved in stage 2

### ISSUE THREAD

**Issue by BroHUAJI** [swathikirans/ego-rnn#8]
Model can be saved in stage 1. But not saved in stage 2.

**Comment by Sid2697** [comment]
@BroHUAJI If you're using a validation set, then [this](https://github.com/swathikirans/ego-rnn/blob/546727664a61b285d2916bf09c2aa45aa628e010/main-run-rgb.py#L200) line should be saving the model for you. 

If you're not using the validation set, then you'll have to edit [this](https://github.com/swathikirans/ego-rnn/blob/546727664a61b285d2916bf09c2aa45aa628e010/main-run-rgb.py#L204) part of the code by associating it with the if statement [here](https://github.com/swathikirans/ego-rnn/blob/546727664a61b285d2916bf09c2aa45aa628e010/main-run-rgb.py#L176). And you'll be saving the model after every 10th epoch.

**Comment by frostinassiky** [comment]
@Sid2697 is correct. I got 62.07% using S2 as the validation set.
